import {
  Injectable,
  Inject,
  BadRequestException,
  InternalServerErrorException,
  NotFoundException,
} from '@nestjs/common';
import {
  ICollateralByKedinasanRepository,
  COLLATERAL_KEDINASAN_EXTERNAL_REPOSITORY,
} from '../../Domain/Repositories/collateral-kedinasan-mou-external.repository';
import { CollateralByKedinasanMOU } from '../../Domain/Entities/collateral-kedinasan-mou-external.entity';
import { CreatePengajuanKedinasanMOUDto } from '../DTOS/dto-Collateral-Kedinasan_MOU/create-collateral-kedinasan.dto';
import { UpdatePengajuanKedinasanMOUDto } from '../DTOS/dto-Collateral-Kedinasan_MOU/update-collateral-kedinasan.dto';

@Injectable()
export class CollateralKedinasanMOUExternalService {
  constructor(
    @Inject(COLLATERAL_KEDINASAN_EXTERNAL_REPOSITORY)
    private readonly repo: ICollateralByKedinasanRepository,
  ) {}

  async create(dto: CreatePengajuanKedinasanMOUDto): Promise<CollateralByKedinasanMOU> {
    const now = new Date();

    if (!dto.pengajuan_id) {
      throw new BadRequestException('Pengajuan ID harus diisi.');
    }

    const collateral = new CollateralByKedinasanMOU(
      { id: dto.pengajuan_id },
      dto.instansi,

      dto.surat_permohonan_kredit,
      dto.surat_pernyataan_penjamin,
      dto.surat_persetujuan_pimpinan,
      dto.surat_keterangan_gaji,

      dto.foto_form_pengajuan,
      dto.foto_surat_kuasa_pemotongan,
      dto.foto_surat_pernyataan_peminjam,
      dto.foto_sk_golongan_terbaru,
      dto.foto_keterangan_tpp,
      dto.foto_biaya_operasional,
      dto.foto_surat_kontrak,
      dto.foto_rekomendasi_bendahara,

      undefined, // ID autogenerated
      now,
      now,
      null,
    );

    try {
      return await this.repo.save(collateral);
    } catch (error) {
      console.error('Create Collateral Kedinasan Error:', error);
      throw new InternalServerErrorException('Gagal membuat collateral kedinasan.');
    }
  }

 async update(id: number, dto: UpdatePengajuanKedinasanMOUDto): Promise<CollateralByKedinasanMOU> {
  const existing = await this.repo.findById(id);
  if (!existing) {
    throw new NotFoundException(`Collateral Kedinasan dengan ID ${id} tidak ditemukan.`);
  }

  // Buat instance baru dengan nilai gabungan antara existing dan dto
  const updated = new CollateralByKedinasanMOU(
    existing.pengajuan,
    dto.instansi ?? existing.instansi,

    dto.surat_permohonan_kredit ?? existing.surat_permohonan_kredit,
    dto.surat_pernyataan_penjamin ?? existing.surat_pernyataan_penjamin,
    dto.surat_persetujuan_pimpinan ?? existing.surat_persetujuan_pimpinan,
    dto.surat_keterangan_gaji ?? existing.surat_keterangan_gaji,

    dto.foto_form_pengajuan ?? existing.foto_form_pengajuan,
    dto.foto_surat_kuasa_pemotongan ?? existing.foto_surat_kuasa_pemotongan,
    dto.foto_surat_pernyataan_peminjam ?? existing.foto_surat_pernyataan_peminjam,
    dto.foto_sk_golongan_terbaru ?? existing.foto_sk_golongan_terbaru,
    dto.foto_keterangan_tpp ?? existing.foto_keterangan_tpp,
    dto.foto_biaya_operasional ?? existing.foto_biaya_operasional,
    dto.foto_surat_kontrak ?? existing.foto_surat_kontrak,
    dto.foto_rekomendasi_bendahara ?? existing.foto_rekomendasi_bendahara,

    existing.id,
    existing.created_at,
    new Date(),
    existing.deleted_at,
  );

  try {
    return await this.repo.update(id, updated);
  } catch (error) {
    console.error('Update Collateral Kedinasan Error:', error);
    throw new InternalServerErrorException('Gagal mengupdate collateral kedinasan.');
  }
}


  async findById(id: number): Promise<CollateralByKedinasanMOU> {
    const collateral = await this.repo.findById(id);
    if (!collateral) {
      throw new NotFoundException(`Collateral Kedinasan dengan ID ${id} tidak ditemukan.`);
    }
    return collateral;
  }

  async findAll(): Promise<CollateralByKedinasanMOU[]> {
    try {
      return await this.repo.findAll();
    } catch (error) {
      console.error('Find All Collateral Kedinasan Error:', error);
      throw new InternalServerErrorException('Gagal mengambil data collateral kedinasan.');
    }
  }

  async delete(id: number): Promise<void> {
    const collateral = await this.repo.findById(id);
    if (!collateral) {
      throw new NotFoundException(`Collateral Kedinasan dengan ID ${id} tidak ditemukan.`);
    }

    try {
      await this.repo.delete(id);
    } catch (error) {
      console.error('Delete Collateral Kedinasan Error:', error);
      throw new InternalServerErrorException('Gagal menghapus collateral kedinasan.');
    }
  }
}
