import {
  Injectable,
  Inject,
  BadRequestException,
  InternalServerErrorException,
  NotFoundException,
} from '@nestjs/common';
import { CollateralByKedinasan_Non_MOU } from '../../Domain/Entities/collateral-kedinasan-non-mou-external.entity';
import { CreatePengajuanKedinasan_Non_MOU_Dto } from '../DTOS/dto-Collateral-Kedinasan_NON_MOU/create-collateral-kedinasan.dto';
import { UpdatePengajuanKedinasan_Non_MOU_Dto } from '../DTOS/dto-Collateral-Kedinasan_NON_MOU/update-collateral-kedinasan.dto';
import {
  COLLATERAL_KEDINASAN_NON_MOU_EXTERNAL_REPOSITORY,
  ICollateralByKedinasan_Non_MOU_Repository,
} from '../../Domain/Repositories/collateral-kedinasan-non-mou-external.repository';

@Injectable()
export class CollateralKedinasan_NonMOU_ExternalService {
  constructor(
    @Inject(COLLATERAL_KEDINASAN_NON_MOU_EXTERNAL_REPOSITORY)
    private readonly repo: ICollateralByKedinasan_Non_MOU_Repository,
  ) {}

  async create(
    dto: CreatePengajuanKedinasan_Non_MOU_Dto,
  ): Promise<CollateralByKedinasan_Non_MOU> {
    const now = new Date();

    if (!dto.pengajuan_id) {
      throw new BadRequestException('Pengajuan ID harus diisi.');
    }

    const collateral = new CollateralByKedinasan_Non_MOU(
      { id: dto.pengajuan_id },
      dto.instansi,

      dto.surat_permohonan_kredit,
      dto.surat_pernyataan_penjamin,
      dto.surat_persetujuan_pimpinan,
      dto.surat_keterangan_gaji,

      dto.foto_keterangan_tpp,
      dto.foto_biaya_operasional,
      dto.foto_surat_kontrak,

      undefined, // ID autogenerated
      now,
      now,
      null,
    );

    try {
      return await this.repo.save(collateral);
    } catch (error) {
      console.error('Create Collateral Kedinasan Error:', error);
      throw new InternalServerErrorException(
        'Gagal membuat collateral kedinasan.',
      );
    }
  }

  async update(
    id: number,
    dto: UpdatePengajuanKedinasan_Non_MOU_Dto,
  ): Promise<CollateralByKedinasan_Non_MOU> {
    const existing = await this.repo.findById(id);
    if (!existing) {
      throw new NotFoundException(
        `Collateral Kedinasan dengan ID ${id} tidak ditemukan.`,
      );
    }

    // Buat instance baru dengan nilai gabungan antara existing dan dto
    const updated = new CollateralByKedinasan_Non_MOU(
      existing.pengajuan,
      dto.instansi ?? existing.instansi,

      dto.surat_permohonan_kredit ?? existing.surat_permohonan_kredit,
      dto.surat_pernyataan_penjamin ?? existing.surat_pernyataan_penjamin,
      dto.surat_persetujuan_pimpinan ?? existing.surat_persetujuan_pimpinan,
      dto.surat_keterangan_gaji ?? existing.surat_keterangan_gaji,
      dto.foto_keterangan_tpp ?? existing.foto_keterangan_tpp,
      dto.foto_biaya_operasional ?? existing.foto_biaya_operasional,
      dto.foto_surat_kontrak ?? existing.foto_surat_kontrak,

      existing.id,
      existing.created_at,
      new Date(),
      existing.deleted_at,
    );

    try {
      return await this.repo.update(id, updated);
    } catch (error) {
      console.error('Update Collateral Kedinasan Error:', error);
      throw new InternalServerErrorException(
        'Gagal mengupdate collateral kedinasan.',
      );
    }
  }

  async findById(id: number): Promise<CollateralByKedinasan_Non_MOU> {
    const collateral = await this.repo.findById(id);
    if (!collateral) {
      throw new NotFoundException(
        `Collateral Kedinasan dengan ID ${id} tidak ditemukan.`,
      );
    }
    return collateral;
  }

  async findAll(): Promise<CollateralByKedinasan_Non_MOU[]> {
    try {
      return await this.repo.findAll();
    } catch (error) {
      console.error('Find All Collateral Kedinasan Error:', error);
      throw new InternalServerErrorException(
        'Gagal mengambil data collateral kedinasan.',
      );
    }
  }

  async delete(id: number): Promise<void> {
    const collateral = await this.repo.findById(id);
    if (!collateral) {
      throw new NotFoundException(
        `Collateral Kedinasan dengan ID ${id} tidak ditemukan.`,
      );
    }

    try {
      await this.repo.delete(id);
    } catch (error) {
      console.error('Delete Collateral Kedinasan Error:', error);
      throw new InternalServerErrorException(
        'Gagal menghapus collateral kedinasan.',
      );
    }
  }
}
